on: push
jobs:
  basic-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.29
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: warehouse
          MYSQL_USER: app-user
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        options: >-
            --health-cmd "mysqladmin ping -h localhost"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: bootstrap modules
        run: npm run bootstrap
      - name: build
        run: npm run build
      - name: populate tables
        run: npm run seed
      - name: run integration tests
        run: npm run test:api