on: push
jobs:
  basic-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: bootstrap modules
        run: npm run bootstrap
      - name: build
        run: npm run build